// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKZXmAN8QEH5UvzO47fYaOxXJ53OSMMg',
    appId: '1:746157274071:web:e39b935badc3016454d192',
    messagingSenderId: '746157274071',
    projectId: 'mealize-1',
    authDomain: 'mealize-1.firebaseapp.com',
    storageBucket: 'mealize-1.firebasestorage.app',
    measurementId: 'G-7KL830RNTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6VuQdGoiw-26r0PpZUp-H5oPG_UN4xY',
    appId: '1:746157274071:android:98736b31a7e3cf7a54d192',
    messagingSenderId: '746157274071',
    projectId: 'mealize-1',
    storageBucket: 'mealize-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjVLzlXcj4OrKCl_YUCLnH95PDYfMudTQ',
    appId: '1:746157274071:ios:d1be4151d90ef2ae54d192',
    messagingSenderId: '746157274071',
    projectId: 'mealize-1',
    storageBucket: 'mealize-1.firebasestorage.app',
    iosBundleId: 'com.example.mealize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjVLzlXcj4OrKCl_YUCLnH95PDYfMudTQ',
    appId: '1:746157274071:ios:d1be4151d90ef2ae54d192',
    messagingSenderId: '746157274071',
    projectId: 'mealize-1',
    storageBucket: 'mealize-1.firebasestorage.app',
    iosBundleId: 'com.example.mealize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOKZXmAN8QEH5UvzO47fYaOxXJ53OSMMg',
    appId: '1:746157274071:web:b32b394e57f85e6754d192',
    messagingSenderId: '746157274071',
    projectId: 'mealize-1',
    authDomain: 'mealize-1.firebaseapp.com',
    storageBucket: 'mealize-1.firebasestorage.app',
    measurementId: 'G-GQD0E270DR',
  );
}